export const socialMediaDetails = [
    {
        icon:'logo-whatsapp',
        link:'https://www.instagram.com/ashertoufeeq',
        color:'#fff',
        size:20,
    },{
        icon:'logo-instagram',
        link:'https://www.facebook.com/ashertoufeeq',
        color:'#fff',
        size:20,
    },{
        icon:'logo-facebook',
        link:'https://www.facebook.com/ashertoufeeq',
        color:'#fff',
        size:20,
    },{
        icon:'ios-mail',
        link:'https://www.facebook.com/ashertoufeeq',
        color:'#fff',
        size:20,
    },
]
